-- \i /home/globi/aliktv/sql/buser.sql
-- \i /root/aliktv/sql/buser.sql
-- create extension if not exists pgcrypto;
drop type if exists brole_type_enum cascade;
create type brole_type_enum as enum('superadmin', 'moder','non','ban','fake');
drop table if exists buser cascade;
CREATE TABLE IF NOT EXISTS buser(
id int generated by default as identity,
pwd VARCHAR (100) NOT NULL,
bname varchar(16) UNIQUE NOT NULL, --unique nickname of a user
email text check(email ~*'^.+@.+\..+$') unique,
brole brole_type_enum NOT NULL default 'non', -- superadmin, moder, non, ban, fake 
crat TIMESTAMP NOT NULL default now()::timestamp, -- created at
ll TIMESTAMP  NOT NULL default now()::timestamp, -- last logined
ava text
);

-- grant all privileges on table session to globi;
insert into buser(pwd,bname, email) values('1234','Globi','globalikslivov@gmail.com');
update buser set brole='superadmin';
-- insert into buser(pwd,bname,email,lng,promo) values('1234', 'dima','dima@yandex.ru','ru',0);
-- insert into buser(pwd,bname, email,brole,lng,promo) values('1234','mickey','marina@yandex.ru','fake','ru',0);

--insert into buser(pwd,bname, email,brole) values('1234','sveta','sveta@yandex.ru','fake');
--insert into buser(pwd,bname, email,brole) values('1234','natasha','natasha@yandex.ru','fake');
-- dob date check(dob < now() - interval '18 years') not null);
-- select age('1973-09-25'::date); select age(dob) from buser; select date_part('year', age(dob)) from buser;
-- date_part('year',interval '45 years 11 mons 27 days'); 45
-- select date_part('year', age(dob)) as dob, bname from buser;

-- alter table buser add column bage int check(bage >=10) not null default 18;
-- alter table buser add column sexor varchar(10) not null default 'hetero';
-- alter table buser add column email text check(email ~*'^.+@.+\..+$') unique;
-- alter table buser add column model boolean not null default false;
-- alter table buser add column items int not null default 0;
-- alter table buser add column rubls numeric not null default 0.00;
-- alter table buser add column proz int not null default 50;
-- alter table buser add column bcard numeric not null default 0;
-- alter table buser add constraint positivcheck check (items >= 0);
-- alter table buser add column ava text;
-- alter table buser add column stat text;


-- alter table buser add column lng varchar(2) not null default 'ru';
-- alter table buser add column promo int not null default 0;
-- alter table buser drop column bcard;

-- alter table  buser add column cadr varchar(40);
