-- \i /home/globi/aliktv/sql/sean.sql
-- \i /root/aliktv/sql/sean.sql
drop table if exists sean;
CREATE TABLE IF NOT EXISTS sean(
id int generated by default as identity,
bname varchar(20),
typ int not null default 0, -- type of stream 0 = all, 1 = privat
crat TIMESTAMP NOT NULL default now()::timestamp, -- beginning of a stream
endat TIMESTAMP NOT NULL default now()::timestamp -- ending of a stream
);
-- insert into sean(sname, typ) values('Globi',0) returning id;
